numpy==1.23.1
scipy==1.8.1
matplotlib
f90nml
fire
beautifulsoup4
Wand
pathlib
path.py
netCDF4
h5py
pymeteo
meteogram-py
nco
cython
subprocess32
geopy
MetPy
siphon
xarray
requests
git+https://github.com/ericleer/wrfconf.git@e87da9fb82026d3c71e2e95ebcc92a289e2c1be4
